name = "lean-lox"
version = "0.1.0"
defaultTargets = ["lean-lox"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "LeanLox"

[[lean_exe]]
name = "lean-lox"
root = "Main"
